version: '3.7'

services:
  modbot:
    image: jasoncky96/telegram-modbot:latest
    container_name: modbot
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]
    restart: always
    networks:
      - modbot
    environment:
      BOT_TOKEN: $BOT_TOKEN
      MODE: PRODUCTION
      DEV_CHAT_ID: $DEV_CHAT_ID
      
      MONGO_USERNAME: $MONGO_USERNAME
      MONGO_PASSWORD: $MONGO_PASSWORD
      MONGO_DB: $MONGO_DB
      MONGO_SERVER: db
      MONGO_PORT: 27017    
    depends_on: 
      - db 

  modbot_pollserver:
    container_name: modbot_pollserver
    image: jasoncky96/telegram-pollingserver:latest
    restart: always
    networks:
      - modbot
    environment:
      BOT_TOKEN: $BOT_TOKEN
      DEV_CHAT_ID: $DEV_CHAT_ID
      POLLING_INTERVAL: "0.2"
      APP_SERVER: modbot
    depends_on: 
      - modbot
      - db 

  db:
    image: mongo:4.4.9-focal
    container_name: modbot_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    volumes:
      - type: volume
        source: modbot-db
        target: /data/db
    networks:
      - modbot

volumes:
  modbot-db:
    driver: local
    name: telegram-modbot_modbot-db

networks:
  modbot: