version: '3.7'

services:
  modbot:
    container_name: modbot
    build:
      context: .
      dockerfile: ./compose/webserver/Dockerfile
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]
    restart: always
    networks:
      - modbot
    environment:
      BOT_TOKEN: $DEVBOT_TOKEN
      MODE: DEBUG
      DEV_CHAT_ID: $DEV_CHAT_ID

      MONGO_USERNAME: $MONGO_USERNAME
      MONGO_PASSWORD: $MONGO_PASSWORD
      MONGO_DB: $MONGO_DB
      MONGO_SERVER: db
      MONGO_PORT: 27017    
    volumes:
      - type: bind
        source: ./app
        target: /code/app
    depends_on: 
      - db 
  
  modbot_pollserver:
    container_name: modbot_pollserver
    build:
      context: .
      dockerfile: ./compose/pollingserver/Dockerfile
    restart: always
    networks:
      - modbot
    environment:
      BOT_TOKEN: $DEVBOT_TOKEN
      MODE: DEBUG
      DEV_CHAT_ID: $DEV_CHAT_ID
      POLLING_INTERVAL: "0.2"
      APP_SERVER: modbot
    depends_on: 
      - modbot
      - db 

  db:
    container_name: modbot_db
    image: mongo:4.4.9-focal
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    volumes:
      - type: volume
        source: modbot-db
        target: /data/db
    networks:
      - modbot

volumes:
  modbot-db:
    driver: local
    name: telegram-modbot_modbot-db

networks:
  modbot: